
import { Inter } from 'next/font/google'
import Navigation from '@/components/Navigation'
import Fter from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Learn more about Ableton - maker of Live and Push | Ableton ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/simplex/bootstrap.min.css" />
        <link rel="shortcut icon" href="/ableton.svg" />
      </head>
      <body className={inter.className}>
        <Navigation />
        {children}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossOrigin="anonymous"></script>
      </body>

        <Fter>
        </Fter>
    </html>
  )
}
